//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int RequestID { get; set; }
        public int ClientID { get; set; }
        public int TourID { get; set; }
        public string Предпочтения { get; set; }
        public string ДополнительныеУслуги { get; set; }
        public string Статус { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
