//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отзывы
    {
        public int ReviewID { get; set; }
        public int ClientID { get; set; }
        public int HotelID { get; set; }
        public int Оценка { get; set; }
        public string Текст { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Отели Отели { get; set; }
    }
}
