//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туры_ТипыТуров
    {
        public int TourID { get; set; }
        public Nullable<int> TourTypeID { get; set; }
    
        public virtual ТипыТуров ТипыТуров { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
